from policyengine_uk.model_api import *


class spi_imputed(Variable):
    label = "SPI imputed"
    documentation = "Whether this household was generated by replacing income variables with SPI imputations."
    entity = Household
    definition_period = YEAR
    value_type = float
    unit = GBP
