from policyengine_uk.model_api import *


class uc_migrated(Variable):
    label = "UC migrated"
    documentation = "Whether this household was generated by migrating an original FRS household to Universal Credit."
    entity = Household
    definition_period = YEAR
    value_type = float
    unit = GBP
