description: Annual allowance for relief on pension contributions
values:
  2015-04-01: 40_000
metadata:
  unit: currency-GBP
  label: Annual allowance for pension contributions
  reference: 
  - title: Tax on your private pension contributions
    href: https://www.gov.uk/tax-on-your-private-pension/annual-allowance
