description: Annual allowance for relief on pension contributions
values:
  2015-04-01: 40_000
  2023-04-06: 60_000
metadata:
  unit: currency-GBP
  label: Annual allowance for pension contributions
  reference:
  - title: Finance Act 2004 s. 228
    href: https://www.legislation.gov.uk/ukpga/2004/12/section/228
  - title: Tax on your private pension contributions
    href: https://www.gov.uk/tax-on-your-private-pension/annual-allowance
