"""
Generates the forecast RPI uprating steps in petrol_and_diesel.yaml.

The statutory schedule ends with the Hydrocarbon Oil Duties Act 1979 rate of
57.95p from 1 March 2027. Budget 2025 states that rates will then be uprated
by RPI from April 2027. This script applies each previous calendar year's RPI
growth from economic_assumptions/yoy_growth.yaml on 1 April (the date in HM
Treasury's Budget 2025 costing), rounding to the nearest hundredth of a penny, and writes the results between the BEGIN and END
markers in petrol_and_diesel.yaml. Run it with --update whenever the RPI
forecast changes; test_fuel_duty_schedule.py fails until you do.

Usage:
    uv run python calculate_fuel_duty_rates.py           # print the steps
    uv run python calculate_fuel_duty_rates.py --update  # rewrite the YAML
"""

import argparse
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

import yaml

FUEL_DUTY_DIR = Path(__file__).resolve().parent
PARAMETER_FILE = FUEL_DUTY_DIR / "petrol_and_diesel.yaml"
YOY_GROWTH_FILE = FUEL_DUTY_DIR.parents[1] / "economic_assumptions" / "yoy_growth.yaml"

# The last statutory rate, and the first and last 1 April steps written out.
# Later steps come from the parameter's uprating metadata.
STATUTORY_DATE = "2027-03-01"
FIRST_UPRATING_YEAR = 2027
LAST_UPRATING_YEAR = 2031

BEGIN = "  # BEGIN RPI forecast generated by calculate_fuel_duty_rates.py\n"
END = "  # END RPI forecast generated by calculate_fuel_duty_rates.py\n"
PENNY_HUNDREDTH = Decimal("0.0001")


def rpi_series() -> dict:
    with open(YOY_GROWTH_FILE) as f:
        return yaml.safe_load(f)["obr"]["rpi"]


def rpi_growth_by_year() -> dict:
    """Calendar-year RPI growth rates keyed by year."""
    values = rpi_series()["values"]
    return {int(str(date)[:4]): Decimal(str(value)) for date, value in values.items()}


def statutory_rate() -> Decimal:
    with open(PARAMETER_FILE) as f:
        values = yaml.safe_load(f)["values"]
    entry = {str(date): value for date, value in values.items()}[STATUTORY_DATE]
    return Decimal(str(entry["value"] if isinstance(entry, dict) else entry))


def forecast_steps() -> list:
    """(date, rate, previous rate, RPI growth) for each forecast 1 April step."""
    growth = rpi_growth_by_year()
    rate = statutory_rate()
    steps = []
    for year in range(FIRST_UPRATING_YEAR, LAST_UPRATING_YEAR + 1):
        previous = rate
        rate = (previous * (1 + growth[year - 1])).quantize(
            PENNY_HUNDREDTH, rounding=ROUND_HALF_UP
        )
        steps.append((f"{year}-04-01", rate, previous, growth[year - 1]))
    return steps


def render(steps: list) -> str:
    # Cite the forecast that yoy_growth.yaml itself cites for RPI.
    forecast = rpi_series()["metadata"]["reference"][0]
    lines = []
    for date, rate, previous, growth in steps:
        lines += [
            f"  {date}:",
            f"    value: {rate}",
            "    metadata:",
            f"      note: Forecast. {previous} uprated by {int(date[:4]) - 1} RPI "
            f"growth of {growth * 100:.1f}%.",
            "      reference:",
            "        - title: Budget 2025 (fuel duty uprated by RPI from April 2027)",
            "          href: https://www.gov.uk/government/publications/budget-2025-document/budget-2025-html",
            "        - title: HM Treasury, Budget 2025 policy costings, page 14 (from 1 April 2027)",
            "          href: https://assets.publishing.service.gov.uk/media/692872fd2a37784b16ecf676/Budget_2025-Policy_Costings.pdf#page=14",
            f"        - title: {forecast['title']} (RPI forecast)",
            f"          href: {forecast['href']}",
        ]
    return "\n".join(lines) + "\n"


def update(steps: list) -> None:
    content = PARAMETER_FILE.read_text()
    start = content.index(BEGIN) + len(BEGIN)
    stop = content.index(END)
    PARAMETER_FILE.write_text(content[:start] + render(steps) + content[stop:])
    print(f"Updated {PARAMETER_FILE}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--update",
        action="store_true",
        help="Rewrite the forecast block in petrol_and_diesel.yaml",
    )
    args = parser.parse_args()
    steps = forecast_steps()
    print(f"{STATUTORY_DATE}: {statutory_rate()} (statutory)")
    for date, rate, previous, growth in steps:
        print(f"{date}: {rate} ({previous} x (1 + {growth}))")
    if args.update:
        update(steps)


if __name__ == "__main__":
    main()
