description: Annual allowance for relief on pension contributions.
values:
  2015-06-01:
    value: 40000
metadata:
  unit: currency-GBP
  reference: https://www.gov.uk/tax-on-your-private-pension/annual-allowance
